/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String PLUGIN_NAME = 'kreki119';
  static const String PLUGIN_VERSION = '1.0.6+6';
  static const String ROBOTO_BOLD = 'Roboto-Bold';
  static const String ROBOTO_ITALIC = 'Roboto-Italic';
  static const String ROBOTO_LIGHT = 'Roboto-Light';
  static const String ROBOTO_MEDIUM = 'Roboto-Medium';
  static const String ROBOTO_REGULAR = 'Roboto-Regular';
  static const String ROBOTO_THIN = 'Roboto-Thin';
}
